#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true
#bspc config focus_follows_pointer true

bspc monitor DP-4 -d 1 2 3 4 5 

bspc config border_width         1
gap=5

#This creates negative padding eaual to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap
bspc config bottom_padding $gap
bspc config left_padding $gap
bspc config right_padding $gap
bspc config -m HDMI-0 top_padding 0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Zathura state=tiled
pgrep /home/stivi/bspswallow/bspswallow || /home/stivi/bspswallow/bspswallow &
xsetroot -cursor_name left_ptr
